#!/bin/bash
#
# Copyright (c) 2018, Konsulko Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Simple script to check if Weston+IVI shell is ready by calling
# LayerManagerControl, optionally waiting for a specified timeout.
#

usage="Usage: weston-ready [-t timeout]" 
timeout=0

function info() { echo "$@" >&2; }

if [ $# -eq 2 ]; then
	if [ $1 = "-t" ]; then
		timeout=$(($2 * 10))
	else
		echo $usage
		exit 1
	fi
fi

info "using timeout $timeout"

time=0
rc=1
while true; do
	if [ $time -gt $timeout ]; then
		info "Timeout reached"
		break
	elif LayerManagerControl get screens >/dev/null 2>&1; then
		info "Weston is now ready"
		rc=0
		break
	fi
	info "waiting..."
	if [ $timeout -gt 0 ]; then
		usleep 500000
	fi
	time=$(($time + 5))
done
exit $rc
