stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
  artifacts:
    name: images
    expose_as: images
    expire_in: 3 days
    paths:
      - images
  cache:
    paths:
      - layers

bbe-poky:
  extends: .build
  script:
    - ./scripts/ci-build.sh $CI_JOB_NAME core-image-base
    - |
      if [[ -n "$B2_KEY_ID" ]]; then
        rclone config create b2 b2 account $B2_KEY_ID key $B2_APP_KEY > /dev/null
        rclone copy --ignore-existing build/sstate-cache/ b2:sc-yocto/poky/sstate/
        rclone copy --ignore-existing build/tmp/deploy/sources/mirror/ b2:sc-yocto/mirror/
      fi

bbe-arago:
  extends: .build
  image: registry.gitlab.com/sancloudltd/buildimg/gcc-arm-9.2:latest
  script:
    - ./scripts/ci-build.sh $CI_JOB_NAME tisdk-base-image tisdk-default-image
    - |
      if [[ -n "$B2_KEY_ID" ]]; then
        rclone config create b2 b2 account $B2_KEY_ID key $B2_APP_KEY > /dev/null
        rclone copy --ignore-existing build/sstate-cache/ b2:sc-yocto/arago/sstate/
        rclone copy --ignore-existing build/tmp/deploy/sources/mirror/ b2:sc-yocto/mirror/
      fi
